### ISSUE TITLE
A second implementation of a pure Rust 3DS usermode library

### ISSUE THREAD

**Issue by phijor** [zaksabeast/libctr-rs#2]
Hey, I just learned of your project from [a Reddit comment](https://old.reddit.com/r/rust/comments/10yk0kg/media_i_spent_time_porting_rust_to_the_nntendo_ds/)! I've been working on a similar (Rust-only) library to run usermode code on the 3DS, https://github.com/phijor/ctru-rt.

Currently, the library implements most [syscalls](https://github.com/phijor/ctru-rt/blob/6ebe83a8b68a70dc869174f816a6b41c35968651/src/svc.rs#L120-L130) (via a proc-macro), does IPC, has an `std`-like [`thread::spawn()`](https://github.com/phijor/ctru-rt/blob/6ebe83a8b68a70dc869174f816a6b41c35968651/src/thread.rs#L193-L200) and implements a few [services](https://github.com/phijor/ctru-rt/tree/main/src/services). The last thing I've been working on was graphics initialization and talking to the GPU via [`gsp::gpu`](https://github.com/phijor/ctru-rt/blob/6ebe83a8b68a70dc869174f816a6b41c35968651/src/services/gsp/gpu.rs#L387-L390).

Right now, I don't have the time to work on the project. I'm posting this to let you know that it exists, in case that is helpful. The code is not as well-commented as it should be and probably contains a bunch of UB, but feel free to ask any questions on how it works!

**Comment by zaksabeast** [comment]
Thanks for the info!  I'll definitely take a look at the code.

libctr-rs is mostly a fun little playground project for me to test a few ideas, reimplement [sysmodules](https://github.com/zaksabeast/3ds-friends-sysmodule), and build other [fun tools](https://github.com/zaksabeast/3ds-Plug-n-play).  I'd probably design it different if I had the time, but two things it provides that I'm interested in are 1) stubs to run tests on non-horizon machines and 2) tools to build sysmodules.

If you have questions about this project, feel free to ask as well!
